VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Steps_report_statistics"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Sub Given_statistics_has_logged_INT_failed_example_eac_9F52A71A20C6(step_expressions As Collection)
    'And statistics has logged {integer} failed example each with a passed, failed and skipped step
    pending
End Sub
